version: "3.8"
services:
  postgres:
    image: postgres
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  redis:
    image: redis
    ports:
      - "6379:6379"
